Repository Lokathor/tinyvec, pull requests merged in 2020-01, with the labels that each got.

#44 Add From<&[T]> and From<&mut [T]> for TinyVec
  src/tinyvec.rs
  tests/tinyvec.rs
Labels: enhancement

#51 Small updates
  src/array.rs
  src/arrayvec.rs
  src/lib.rs
  src/tinyvec.rs
Labels: documentation, enhancement

#57 Makes `tiny_vec!` go directly to the heap if the CAPACITY would have overflowed.
  src/tinyvec.rs
Labels: Performance
